# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

volumes:
  peer3.org1.example.com:

networks:
  test:
    name: fabric_test

services:

  peer3.org1.example.com:
    container_name: peer$PEER_ID.org$ORG_ID.example.com
    image: hyperledger/fabric-peer:latest
    labels:
      service: hyperledger-fabric
    environment:
      #Generic peer variables
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      # the following setting starts chaincode containers on the same
      # bridge network as the peers
      # https://docs.docker.com/compose/networking/
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=fabric_test
      - FABRIC_LOGGING_SPEC=INFO
      #- FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      # Peer specific variabes
      - CORE_PEER_ID=peer$PEER_ID.org$ORG_ID.example.com
      - CORE_PEER_ADDRESS=peer$PEER_ID.org$ORG_ID.example.com:$PEER_PORT
      - CORE_PEER_LISTENADDRESS=0.0.0.0:$PEER_PORT
      - CORE_PEER_CHAINCODEADDRESS=peer$PEER_ID.org$ORG_ID.example.com:$PEER_CHAINCODE_PORT
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:$PEER_CHAINCODE_PORT
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer$PEER_ID.org$ORG_ID.example.com:$PEER_PORT
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer$PEER_ID.org$ORG_ID.example.com:$PEER_PORT
      - CORE_PEER_LOCALMSPID=Org${ORG_ID}MSP
    volumes:
        - /var/run/:/host/var/run/
        - $CRYPTO_DIR/msp:/etc/hyperledger/fabric/msp
        - $CRYPTO_DIR/tls:/etc/hyperledger/fabric/tls
        - $TEST_NET_PATH/peer$PEER_ID.org$ORG_ID.example.com:/var/hyperledger/production
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    ports:
      - $PEER_PORT:$PEER_PORT
    networks:
      - test

